mysql:
  host: 127.0.0.1
  port: 3306
  db: gvb_db
  user: root
  password: qq123123
  log_level: dev
  config: ""
logger:
  level: info
  prefix: "[gvb]"
  director: log
  show_line: true
  log_in_console: true
system:
  host: 0.0.0.0
  port: 4000
  env: release
site_info:
  created_at: "2023-02-12"
  filing: 湘ICP备xxxxx号
  title: 个人博客
  qq_image: https://avatars.githubusercontent.com/u/9919?s=80&v=4
  version: 0.0.1
  email: kexin@korix.com
  wechat_image: https://avatars.githubusercontent.com/u/9919?s=80&v=4
  name: KORIX
  job: FE
  addr: Earth
  slogan: "~"
  slogan_en: ~~
  web: https://github.com/Kori000
  bilibili_url: https://github.com/Kori000
  gitee_url: https://github.com/Kori000
  github_urt: https://github.com/Kori000
qq:
  app_id: "123"
  key: "123"
  redirect: "123"
email:
  host: "1"
  port: 0
  user: "23"
  password: "23"
  default_from_email: "23"
  use_ssl: false
  user_tls: false
qiniu:
  enable: false
  access_key: "123"
  secret_key: "123"
  bucket: "123"
  cdn: "123"
  zone: "213"
  size: 0
jwt:
  secret: "213"
  expires: 0
  issuer: "213"
