// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/advertisement/create": {
            "post": {
                "description": "广告新增",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "广告管理"
                ],
                "summary": "广告新增",
                "parameters": [
                    {
                        "description": "广告信息",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/advertisement_api.AdvertRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/advertisement/edit": {
            "post": {
                "description": "广告编辑",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "广告管理"
                ],
                "summary": "广告编辑",
                "parameters": [
                    {
                        "description": " ",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/advertisement_api.AdvertEditBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/advertisement/list": {
            "get": {
                "description": "广告列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "广告管理"
                ],
                "summary": "广告列表",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "name": "page_size",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/advertisement/remove": {
            "post": {
                "description": "广告删除",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "广告管理"
                ],
                "summary": "广告删除",
                "parameters": [
                    {
                        "description": " ",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.RemoveRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/banner/edit": {
            "post": {
                "description": "图片编辑",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "图片管理"
                ],
                "summary": "图片编辑",
                "parameters": [
                    {
                        "description": " ",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/banners_api.BannersEditBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/banner/list": {
            "get": {
                "description": "图片列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "图片管理"
                ],
                "summary": "图片列表",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "name": "page_size",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/banner/name/list": {
            "get": {
                "description": "获取图片名称列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "图片管理"
                ],
                "summary": "图片名称列表",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/banner/remove": {
            "post": {
                "description": "图片批量删除",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "图片管理"
                ],
                "summary": "图片批量删除",
                "parameters": [
                    {
                        "description": " ",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.RemoveRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/banner/upload": {
            "post": {
                "description": "图片新增 - 服务器直传",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "图片管理"
                ],
                "summary": "图片新增 - 服务器直传",
                "parameters": [
                    {
                        "type": "array",
                        "items": {
                            "type": "file"
                        },
                        "collectionFormat": "csv",
                        "description": "图片",
                        "name": "images",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/banner/upload/url": {
            "post": {
                "description": "图片新增 - 地址形式",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "图片管理"
                ],
                "summary": "图片新增 - 地址形式",
                "parameters": [
                    {
                        "description": "图片",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/banners_api.OssUploadBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/menu/create": {
            "post": {
                "description": "菜单新增",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "菜单管理"
                ],
                "summary": "菜单新增",
                "parameters": [
                    {
                        "description": "菜单信息",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/menu_api.MenuRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/menu/list": {
            "get": {
                "description": "菜单列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "菜单管理"
                ],
                "summary": "菜单列表",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/menu/name/list": {
            "get": {
                "description": "菜单列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "菜单管理"
                ],
                "summary": "菜单列表",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/settings/email": {
            "get": {
                "description": "关于邮件 - 获取",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "系统配置管理"
                ],
                "summary": "关于邮件 - 获取",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "put": {
                "description": "关于邮件 - 编辑",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统配置管理"
                ],
                "summary": "关于邮件 - 编辑",
                "parameters": [
                    {
                        "description": " ",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/config.Email"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/settings/jwt": {
            "get": {
                "description": "关于JWT - 获取",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "系统配置管理"
                ],
                "summary": "关于JWT - 获取",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "put": {
                "description": "关于JWT - 编辑",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统配置管理"
                ],
                "summary": "关于JWT - 编辑",
                "parameters": [
                    {
                        "description": " ",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/config.JWT"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/settings/qiniu": {
            "get": {
                "description": "关于七牛云 - 获取",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "系统配置管理"
                ],
                "summary": "关于七牛云 - 获取",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "put": {
                "description": "关于七牛云 - 编辑",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统配置管理"
                ],
                "summary": "关于七牛云 - 编辑",
                "parameters": [
                    {
                        "description": " ",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/config.QiNiu"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/settings/qq": {
            "get": {
                "description": "关于QQ - 获取",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "系统配置管理"
                ],
                "summary": "关于QQ - 获取",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "put": {
                "description": "关于QQ - 编辑",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统配置管理"
                ],
                "summary": "关于QQ - 编辑",
                "parameters": [
                    {
                        "description": " ",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/config.QQ"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/settings/site": {
            "get": {
                "description": "关于站点 - 获取",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "系统配置管理"
                ],
                "summary": "关于站点 - 获取",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "put": {
                "description": "关于站点 - 编辑",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统配置管理"
                ],
                "summary": "关于站点 - 编辑",
                "parameters": [
                    {
                        "description": " ",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/config.SiteInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/test": {
            "get": {
                "description": "功能测试",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "测试模块"
                ],
                "summary": "功能测试",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/token/qiniu": {
            "get": {
                "description": "七牛云Token - 获取",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Token管理"
                ],
                "summary": "七牛云Token - 获取",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        }
    },
    "definitions": {
        "advertisement_api.AdvertEditBody": {
            "type": "object",
            "required": [
                "href",
                "images",
                "is_show",
                "title"
            ],
            "properties": {
                "href": {
                    "type": "string",
                    "default": "https://avatars.githubusercontent.com/u/9919?s=80\u0026v=4"
                },
                "id": {
                    "type": "integer"
                },
                "images": {
                    "type": "string",
                    "default": "https://avatars.githubusercontent.com/u/9919?s=80\u0026v=4"
                },
                "is_show": {
                    "type": "boolean",
                    "default": true
                },
                "title": {
                    "type": "string",
                    "default": "名称"
                }
            }
        },
        "advertisement_api.AdvertRequest": {
            "type": "object",
            "required": [
                "href",
                "images",
                "is_show",
                "title"
            ],
            "properties": {
                "href": {
                    "type": "string",
                    "default": "https://avatars.githubusercontent.com/u/9919?s=80\u0026v=4"
                },
                "images": {
                    "type": "string",
                    "default": "https://avatars.githubusercontent.com/u/9919?s=80\u0026v=4"
                },
                "is_show": {
                    "type": "boolean",
                    "default": true
                },
                "title": {
                    "type": "string",
                    "default": "名称"
                }
            }
        },
        "banners_api.BannersEditBody": {
            "type": "object",
            "required": [
                "name",
                "origin_type"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "description": "图片名称",
                    "type": "string"
                },
                "origin_type": {
                    "description": "图片来源",
                    "allOf": [
                        {
                            "$ref": "#/definitions/ctype.ImageType"
                        }
                    ]
                }
            }
        },
        "banners_api.OssUploadBody": {
            "type": "object",
            "required": [
                "image_list"
            ],
            "properties": {
                "image_list": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "config.Email": {
            "type": "object",
            "properties": {
                "default_from_email": {
                    "description": "默认的发件人名字",
                    "type": "string",
                    "default": "23"
                },
                "host": {
                    "type": "string",
                    "default": "1"
                },
                "password": {
                    "type": "string",
                    "default": "23"
                },
                "port": {
                    "type": "integer",
                    "default": 0
                },
                "use_ssl": {
                    "description": "是否使用 ssl",
                    "type": "boolean",
                    "default": false
                },
                "user": {
                    "description": "发件人邮箱",
                    "type": "string",
                    "default": "23"
                },
                "user_tls": {
                    "type": "boolean",
                    "default": false
                }
            }
        },
        "config.JWT": {
            "type": "object",
            "properties": {
                "expires": {
                    "description": "过期时间",
                    "type": "integer",
                    "default": 0
                },
                "issuer": {
                    "description": "签发者",
                    "type": "string",
                    "default": "213"
                },
                "secret": {
                    "description": "秘钥",
                    "type": "string",
                    "default": "213"
                }
            }
        },
        "config.QQ": {
            "type": "object",
            "properties": {
                "app_id": {
                    "type": "string",
                    "default": "123"
                },
                "key": {
                    "type": "string",
                    "default": "123"
                },
                "redirect": {
                    "description": "重定向地址",
                    "type": "string",
                    "default": "123"
                }
            }
        },
        "config.QiNiu": {
            "type": "object",
            "properties": {
                "access_key": {
                    "type": "string",
                    "default": "DSiVMvhK1idyOSeVpu4XBu0WR5vDKjNjosvGGGsA"
                },
                "bucket": {
                    "description": "存储桶名称",
                    "type": "string",
                    "default": "kori-foreign"
                },
                "cdn": {
                    "description": "访问的地址前缀",
                    "type": "string",
                    "default": "123"
                },
                "enable": {
                    "description": "是否启用",
                    "type": "boolean",
                    "default": true
                },
                "secret_key": {
                    "type": "string",
                    "default": "oDJjQW4psIwzUvA4q-XyVSs1kBrrXtzlPWE5HeAR"
                },
                "size": {
                    "description": "存储的大小限制, 单位 MB",
                    "type": "number",
                    "default": 0
                },
                "zone": {
                    "description": "存储的地区",
                    "type": "string",
                    "default": "213"
                }
            }
        },
        "config.SiteInfo": {
            "type": "object",
            "properties": {
                "addr": {
                    "type": "string",
                    "default": "Earth"
                },
                "bilibili_url": {
                    "type": "string",
                    "default": "https://github.com/Kori000"
                },
                "created_at": {
                    "type": "string",
                    "default": "2023-02-12"
                },
                "email": {
                    "type": "string",
                    "default": "kexin@korix.com"
                },
                "filing": {
                    "type": "string",
                    "default": "湘ICP备xxxxx号"
                },
                "gitee_url": {
                    "type": "string",
                    "default": "https://github.com/Kori000"
                },
                "github_urt": {
                    "type": "string",
                    "default": "https://github.com/Kori000"
                },
                "job": {
                    "type": "string",
                    "default": "FE"
                },
                "name": {
                    "type": "string",
                    "default": "KORIX"
                },
                "qq_image": {
                    "type": "string",
                    "default": "https://avatars.githubusercontent.com/u/9919?s=80\u0026v=4"
                },
                "slogan": {
                    "type": "string",
                    "default": "~"
                },
                "slogan_en": {
                    "type": "string",
                    "default": "~~"
                },
                "title": {
                    "type": "string",
                    "default": "个人博客"
                },
                "version": {
                    "type": "string",
                    "default": "0.0.1"
                },
                "web": {
                    "type": "string",
                    "default": "https://github.com/Kori000"
                },
                "wechat_image": {
                    "type": "string",
                    "default": "https://avatars.githubusercontent.com/u/9919?s=80\u0026v=4"
                }
            }
        },
        "ctype.ImageType": {
            "type": "integer",
            "enum": [
                1,
                2
            ],
            "x-enum-comments": {
                "Local": "本地服务器",
                "QiNiu": "七牛云"
            },
            "x-enum-varnames": [
                "Local",
                "QiNiu"
            ]
        },
        "menu_api.ImageSort": {
            "type": "object",
            "properties": {
                "image_id": {
                    "type": "integer"
                },
                "sort": {
                    "type": "integer"
                }
            }
        },
        "menu_api.MenuRequest": {
            "type": "object",
            "required": [
                "path",
                "sort",
                "title"
            ],
            "properties": {
                "abstract": {
                    "description": "简介",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "abstract_time": {
                    "description": "简介的切换时间",
                    "type": "integer"
                },
                "banner_time": {
                    "description": "菜单图片的切换时间 0 表示不切换",
                    "type": "integer"
                },
                "image_sort_list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/menu_api.ImageSort"
                    }
                },
                "path": {
                    "type": "string"
                },
                "slogan": {
                    "type": "string"
                },
                "sort": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "models.RemoveRequest": {
            "type": "object",
            "required": [
                "id_list"
            ],
            "properties": {
                "id_list": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "integer"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "127.0.0.1:4000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
