basePath: /
definitions:
  advertisement_api.AdvertEditBody:
    properties:
      href:
        default: https://avatars.githubusercontent.com/u/9919?s=80&v=4
        type: string
      id:
        type: integer
      images:
        default: https://avatars.githubusercontent.com/u/9919?s=80&v=4
        type: string
      is_show:
        default: true
        type: boolean
      title:
        default: 名称
        type: string
    required:
    - href
    - images
    - is_show
    - title
    type: object
  advertisement_api.AdvertRequest:
    properties:
      href:
        default: https://avatars.githubusercontent.com/u/9919?s=80&v=4
        type: string
      images:
        default: https://avatars.githubusercontent.com/u/9919?s=80&v=4
        type: string
      is_show:
        default: true
        type: boolean
      title:
        default: 名称
        type: string
    required:
    - href
    - images
    - is_show
    - title
    type: object
  banners_api.BannersEditBody:
    properties:
      id:
        type: integer
      name:
        description: 图片名称
        type: string
      origin_type:
        allOf:
        - $ref: '#/definitions/ctype.ImageType'
        description: 图片来源
    required:
    - name
    - origin_type
    type: object
  banners_api.OssUploadBody:
    properties:
      image_list:
        items:
          type: string
        type: array
    required:
    - image_list
    type: object
  config.Email:
    properties:
      default_from_email:
        default: "23"
        description: 默认的发件人名字
        type: string
      host:
        default: "1"
        type: string
      password:
        default: "23"
        type: string
      port:
        default: 0
        type: integer
      use_ssl:
        default: false
        description: 是否使用 ssl
        type: boolean
      user:
        default: "23"
        description: 发件人邮箱
        type: string
      user_tls:
        default: false
        type: boolean
    type: object
  config.JWT:
    properties:
      expires:
        default: 0
        description: 过期时间
        type: integer
      issuer:
        default: "213"
        description: 签发者
        type: string
      secret:
        default: "213"
        description: 秘钥
        type: string
    type: object
  config.QQ:
    properties:
      app_id:
        default: "123"
        type: string
      key:
        default: "123"
        type: string
      redirect:
        default: "123"
        description: 重定向地址
        type: string
    type: object
  config.QiNiu:
    properties:
      access_key:
        default: DSiVMvhK1idyOSeVpu4XBu0WR5vDKjNjosvGGGsA
        type: string
      bucket:
        default: kori-foreign
        description: 存储桶名称
        type: string
      cdn:
        default: "123"
        description: 访问的地址前缀
        type: string
      enable:
        default: true
        description: 是否启用
        type: boolean
      secret_key:
        default: oDJjQW4psIwzUvA4q-XyVSs1kBrrXtzlPWE5HeAR
        type: string
      size:
        default: 0
        description: 存储的大小限制, 单位 MB
        type: number
      zone:
        default: "213"
        description: 存储的地区
        type: string
    type: object
  config.SiteInfo:
    properties:
      addr:
        default: Earth
        type: string
      bilibili_url:
        default: https://github.com/Kori000
        type: string
      created_at:
        default: "2023-02-12"
        type: string
      email:
        default: kexin@korix.com
        type: string
      filing:
        default: 湘ICP备xxxxx号
        type: string
      gitee_url:
        default: https://github.com/Kori000
        type: string
      github_urt:
        default: https://github.com/Kori000
        type: string
      job:
        default: FE
        type: string
      name:
        default: KORIX
        type: string
      qq_image:
        default: https://avatars.githubusercontent.com/u/9919?s=80&v=4
        type: string
      slogan:
        default: "~"
        type: string
      slogan_en:
        default: ~~
        type: string
      title:
        default: 个人博客
        type: string
      version:
        default: 0.0.1
        type: string
      web:
        default: https://github.com/Kori000
        type: string
      wechat_image:
        default: https://avatars.githubusercontent.com/u/9919?s=80&v=4
        type: string
    type: object
  ctype.ImageType:
    enum:
    - 1
    - 2
    type: integer
    x-enum-comments:
      Local: 本地服务器
      QiNiu: 七牛云
    x-enum-varnames:
    - Local
    - QiNiu
  models.RemoveRequest:
    properties:
      id_list:
        items:
          type: integer
        minItems: 1
        type: array
    required:
    - id_list
    type: object
host: 127.0.0.1:4000
info:
  contact: {}
  version: 1.0.0
paths:
  /api/advertisement/create:
    post:
      consumes:
      - application/json
      description: 广告新增
      parameters:
      - description: 广告信息
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/advertisement_api.AdvertRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: 广告新增
      tags:
      - 广告管理
  /api/advertisement/edit:
    post:
      consumes:
      - application/json
      description: 广告编辑
      parameters:
      - description: ' '
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/advertisement_api.AdvertEditBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: 广告编辑
      tags:
      - 广告管理
  /api/advertisement/list:
    get:
      consumes:
      - application/json
      description: 广告列表
      parameters:
      - default: 1
        in: query
        name: page
        required: true
        type: integer
      - default: 10
        in: query
        name: page_size
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: 广告列表
      tags:
      - 广告管理
  /api/advertisement/remove:
    post:
      consumes:
      - application/json
      description: 广告删除
      parameters:
      - description: ' '
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.RemoveRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: 广告删除
      tags:
      - 广告管理
  /api/banner/edit:
    post:
      consumes:
      - application/json
      description: 图片编辑
      parameters:
      - description: ' '
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/banners_api.BannersEditBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: 图片编辑
      tags:
      - 图片管理
  /api/banner/list:
    get:
      consumes:
      - application/json
      description: 图片列表
      parameters:
      - default: 1
        in: query
        name: page
        required: true
        type: integer
      - default: 10
        in: query
        name: page_size
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: 图片列表
      tags:
      - 图片管理
  /api/banner/remove:
    post:
      consumes:
      - application/json
      description: 图片批量删除
      parameters:
      - description: ' '
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.RemoveRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: 图片批量删除
      tags:
      - 图片管理
  /api/banner/upload:
    post:
      consumes:
      - multipart/form-data
      description: 图片新增 - 服务器直传
      parameters:
      - collectionFormat: csv
        description: 图片
        in: formData
        items:
          type: file
        name: images
        required: true
        type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: 图片新增 - 服务器直传
      tags:
      - 图片管理
  /api/banner/upload/url:
    post:
      consumes:
      - multipart/form-data
      description: 图片新增 - 地址形式
      parameters:
      - description: 图片
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/banners_api.OssUploadBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: 图片新增 - 地址形式
      tags:
      - 图片管理
  /api/settings/email:
    get:
      consumes:
      - application/json
      description: 关于邮件 - 获取
      responses:
        "200":
          description: OK
      summary: 关于邮件 - 获取
      tags:
      - 系统配置管理
    put:
      consumes:
      - application/json
      description: 关于邮件 - 编辑
      parameters:
      - description: ' '
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/config.Email'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: 关于邮件 - 编辑
      tags:
      - 系统配置管理
  /api/settings/jwt:
    get:
      consumes:
      - application/json
      description: 关于JWT - 获取
      responses:
        "200":
          description: OK
      summary: 关于JWT - 获取
      tags:
      - 系统配置管理
    put:
      consumes:
      - application/json
      description: 关于JWT - 编辑
      parameters:
      - description: ' '
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/config.JWT'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: 关于JWT - 编辑
      tags:
      - 系统配置管理
  /api/settings/qiniu:
    get:
      consumes:
      - application/json
      description: 关于七牛云 - 获取
      responses:
        "200":
          description: OK
      summary: 关于七牛云 - 获取
      tags:
      - 系统配置管理
    put:
      consumes:
      - application/json
      description: 关于七牛云 - 编辑
      parameters:
      - description: ' '
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/config.QiNiu'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: 关于七牛云 - 编辑
      tags:
      - 系统配置管理
  /api/settings/qq:
    get:
      consumes:
      - application/json
      description: 关于QQ - 获取
      responses:
        "200":
          description: OK
      summary: 关于QQ - 获取
      tags:
      - 系统配置管理
    put:
      consumes:
      - application/json
      description: 关于QQ - 编辑
      parameters:
      - description: ' '
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/config.QQ'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: 关于QQ - 编辑
      tags:
      - 系统配置管理
  /api/settings/site:
    get:
      consumes:
      - application/json
      description: 关于站点 - 获取
      responses:
        "200":
          description: OK
      summary: 关于站点 - 获取
      tags:
      - 系统配置管理
    put:
      consumes:
      - application/json
      description: 关于站点 - 编辑
      parameters:
      - description: ' '
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/config.SiteInfo'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: 关于站点 - 编辑
      tags:
      - 系统配置管理
  /api/token/qiniu:
    get:
      consumes:
      - application/json
      description: 七牛云Token - 获取
      responses:
        "200":
          description: OK
      summary: 七牛云Token - 获取
      tags:
      - Token管理
swagger: "2.0"
